org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=768m
kotlin.daemon.jvmargs=-Xmx512m
kotlin.native.jvmArgs=-Xmx9216m
org.gradle.configuration-cache=true
org.gradle.caching=false
